package consts

const (
	STATEMENT_TYPE_Q = "SELECT"
	STATEMENT_TYPE_U = "UPDATE"
	STATEMENT_TYPE_D = "DELETE"
	STATEMENT_TYPE_I = "INSERT"
	STATEMENT_TYPE_S = "SQL"
)

//默认工作空间
const DEFAULT_NAMESPACE = "DEFAULT"

const DB_TYPE_SQLITE3  ="sqlite3"