package consts

const (
	STATEMENT_TYPE_Q = "SELECT"
	STATEMENT_TYPE_U = "UPDATE"
	STATEMENT_TYPE_D = "DELETE"
	STATEMENT_TYPE_I = "INSERT"
	STATEMENT_TYPE_S = "SQL"
)

const DEFAULT_NAMESPACE = "DEFAULT"
